@urlDev=http://localhost:8000/level

### Create level
POST  {{urlDev}}/
Content-Type: application/json

{
    "name": "b1"
}

### Get all levels
GET   {{urlDev}}/

### Update level
PATCH {{urlDev}}/2
Content-Type: application/json

{
    "name": "A1"
}

### Delete level
DELETE  {{urlDev}}/2

