@urlDev=http://localhost:8000/apis/specialization

### Create specialization
POST  {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNjk5NTQ1OTg3LCJleHAiOjE2OTk1NTMxODd9.M191Brri7UXXY3L91vAByUcyUarPu_0dMIVjSeVEww0
Content-Type: application/json

{
    "name": "test1"
}

### Get all specializations
GET   {{urlDev}}/

### Update specialization
PATCH {{urlDev}}/2
Content-Type: application/json

{
    "name": "test31"
}

### Delete specialization
DELETE  {{urlDev}}/2

