@urlDev=http://localhost:8000/apis/type

### Create level
POST  {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNjk5NTQ1OTg3LCJleHAiOjE2OTk1NTMxODd9.M191Brri7UXXY3L91vAByUcyUarPu_0dMIVjSeVEww0
Content-Type: application/json

{
    "name": "test 3",
    "isWord": false
}

### Get all levels
GET   {{urlDev}}/false

### Update level
PATCH {{urlDev}}/3
Content-Type: application/json

{
    "name": "test 2",
    "isWord": true
}

### Delete level
DELETE  {{urlDev}}/2
