@urlDev=http://localhost:8000/apis/word

### Create word
POST  {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2OTk3OTU0MjQsImV4cCI6MTY5OTgwMjYyNH0.mpyrIaj4J8XI3e-k--iHLrPqS5b-5GHS7-1Hmx9k-nw
Content-Type: application/json

{
    "typeId": 2,
    "topicId": [2],          
    "levelId": 2,
    "specializationId": 2,
    "content": "dddd",
    "mean": "test word 1",
    "note": "test",
    "examples": ["test", "test1"]
}

### Get all words
GET   {{urlDev}}?sort=desc

### Get one word
GET   {{urlDev}}/3

### Update wordd
PATCH {{urlDev}}/3
Content-Type: application/json

{
    "typeId": 1,
    "topicId": [1],          
    "levelId": 1,
    "specializationId": 1,
    "content": "hello world 56",
    "mean": "test 1",
    "note": "test 1",
    "phonetic": "test 1",
    "examples": ["test"],
    "picture": "test"
}

### Delete word
DELETE  {{urlDev}}/2