@urlDev=http://localhost:8000/apis/word

### Create word
POST  {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNjk5NTQ0MzcwLCJleHAiOjE2OTk1NTE1NzB9.iamg7URW6K2UzJC18ktP2wZACWWlf6fikBUB-b0u0gg
Content-Type: application/json

{
    "typeId": 1,
    "topicId": [1],          
    "levelId": 1,
    "specializationId": 1,
    "content": "d",
    "mean": "test word 1",
    "note": "test",
    "examples": ["test", "test1"]
}

### Get all words
GET   {{urlDev}}?sort=desc

### Get one word
GET   {{urlDev}}/3

### Update wordd
PATCH {{urlDev}}/3
Content-Type: application/json

{
    "typeId": 1,
    "topicId": [1],          
    "levelId": 1,
    "specializationId": 1,
    "content": "hello world 56",
    "mean": "test 1",
    "note": "test 1",
    "phonetic": "test 1",
    "examples": ["test"],
    "picture": "test"
}

### Delete word
DELETE  {{urlDev}}/2